const link = document.getElementById('translater');
let language = localStorage.getItem('currentLanguage') || 'en';

link.addEventListener('click', function (event) {
    event.preventDefault();
    language = language === 'en' ? 'ru' : 'en';

    getTranslate();
});

function getTranslate() {
    localStorage.setItem('currentLanguage', language);

    const elements = document.querySelectorAll('[data-i18n]');

    elements.forEach((element) => {
        const translationKey = element.dataset.i18n;

        if (i18n.hasOwnProperty(language) && i18n[language].hasOwnProperty(translationKey)) {
            element.textContent = i18n[language][translationKey];
        }
    });
}

const i18n = {
    'en': {
  'header__logo': 'HEALTHCARE',
  'menu__link-home': 'Home',
  'menu__link-about': 'About',
  'menu__link-article': 'Article',
  'menu__link-services': 'Services',
  'get__started': 'Get Started',
  'body-search__titl': 'Find And Search Your Suitable Doctor’s',
  'body-search__text': 'Join us and take care of yourself and your family with health services that will make you feel confident and safe in your daily life.',
  'select-NY': 'New York, USA',
  'select-2': 'Пункт №2',
  'select-3': 'Пункт №3',
  'select-4': 'Пункт №4',
  'solution__titl': '3 Easy Steps and Get Your Solution',
  'items-solution__titl': 'Find best doctor’s',
  'items-solution__titl_get_appointment': 'Get Appointment',
  'items-solution__text_askfor': 'Ask for an appointment of the doctor quickly with almost a single click. We take care of the rest.',
  'items-solution__titl_happycons': 'Happy Consultations',
  'items-solution__text_consulations': 'Do consultations and take the service based on your appointment. Get back to good health',
  'titl-doctor__name': 'Dr. Khalid Abbed',
  'titl-doctor__rating': 'Carddiologist (MBBS) 5.0',
  'item-doctor__text': 'Experience',
  'item-doctor__number': '5 Years',
  'item-doctor__text2': 'Patients',
  'item-doctor__text3': 'Reviews',
  'item-doctor__number': '3.5K',
  'item-doctor__number': '2.5K',
  'footer-doctor__text': 'Mayo Clinic Hospital',
  'main-dictor__titl': 'Best quality service with our experience doctors',
  'main-dictor__text': 'With our top doctors, we are able to provide best medical services above average. We have highly experienced doctors, so don\'t worry. They are also very talented in their fields',
  'services-doctor__servis': 'Search your specialist & Online consultations anywhere',
  'services-doctor__servis2': 'Consultation our top specialists',
  'services-doctor__servis3': 'Doctors are available 24/7',
  'header-service__titl': 'Our Service',
  'header-service__text': 'Our doctors have high qualified skills and are guaranteed to help you recover from your disease.',
  'item-service__cardiology': 'Cardiology',
  'header-service__text_cardiology': 'Our cardiologists are skilled at the diagnosing and treating diseases of the cardiovascular system.',
  'item-service__pulmonology': 'Pulmonology',
  'item-service__text_pulm': 'Our Pulmonologist are skilled at diagnosing treating diseases of the Pulmonology system.',
  'item-service__titl_medecine': 'Medicine',
  'item-service__text_medecine': 'Our medcine doctor are skilled at diagnosing treating diseases of the latest medicine system.',
  'online__titl': 'Meet Our Certified Online Doctors',
  'online__text': 'Our online doctors have an average of 15 years experience and a 98% satisfaction rating, they really set us apart!',
  'body-ite__text': 'Dentist Specialist',
  'body-ite__text2': 'Carddiologist Specialist',
  'body-ite__text3': 'Neurology Specialist',
  'body-ite__text4': 'Cancer Specialist',
  'explore_all_doctors': 'Explore All Doctors',
  'body-apps__titl': 'Mobile apps are available. Get HealthCare for free!',
  'body-apps__text': 'Get on-demand access to a doctor on your phone with the free HealthCare mobile app. Download and register on our app for free and feel safe for all your family.',
  'rigth-footer__titl': 'Subscribe newsletter',
  'rigth-footer__text': 'Sign up for tips, new destinations, and exclusive promos.',
  'rigth-footer__button': 'Subscribe',
  'category__item_home': 'Home',
  'category__item_about': 'About',
  'category__item_services': 'Services',
  'category__item_reviews': 'Reviews',
  'category__item_article': 'Article',
  'left-footer__adress': 'Metairie, 3689 Bassel Street, LA, Louisiana',
  'left-footer__tell': 'Contact us: 225-788-5489',
  'futer__licenzion': '© 2021 Healthcare - All rights reserved.',
  'futer__priv-item': 'Privacy',
  'futer__priv-item2': 'Security',
  'futer__priv-item3': 'Terms',
  'clients__titl': 'Look our Clients have to say about us',
  'item-clients__text': 'Telehealth is fueled by digital technologies and DocTime telemedicine app has brought a great revolution in medical services specially an overpopulated country where virtual chamber can create at anywhere thoughout country',
  'item-clients__text2': 'I visited my PCP for abdominal pain. My doctor told me that I need to see Gastroenterologist. Earlier I used to call multiple offices to schedule an appointment that suites my time.',
  'item-clients__text3': 'HealthCare is enlightens my superpower each and every time...! I find DocTime a brand-able telemedicine platform with virtual waiting room, video consultation, e-prescription, beautifully planned user interface. Thank you.',
  'body-apoitment__titl': 'It’s time change your life today',
  'book_an_appoinment': 'Book an Appoinment',
  'category__titl': 'Category',
  'about__item': 'Partners',
  'about__item2': 'Careers',
  'about__item3': 'Press',
  'about__item4': 'Community',
  'about__titl': 'About',
  'switch__theme': 'Switch Theme',

    },
    'ru': {
  'header__logo': 'HEALTHCARE',
  'menu__link-home': 'Главная',
  'menu__link-about': 'О нас',
  'menu__link-article': 'Статьи',
  'menu__link-services': 'Услуги',
  'get__started': 'Начать',
  'body-search__titl': 'Найдите и выберите себе врача',
  'body-search__text': 'Присоединяйтесь к нам и заботьтесь о себе и своей семье с услугами по уходу за здоровьем, которые помогут вам чувствовать себя уверенно и безопасно в повседневной жизни.',
  'select-NY': 'Нью-Йорк, США',
  'select-2': 'Пункт №2',
  'select-3': 'Пункт №3',
  'select-4': 'Пункт №4',
  'solution__titl': '3 простых шага и получите свое решение',
  'items-solution__text': 'Найдите своего врача легко с минимумом усилий. Мы всё организовали для вас.',
  'items-solution__titl_get_appointment': 'Записаться на прием',
  'items-solution__text_askfor': 'Запросите прием к врачу быстро, почти в один клик. Остальное мы возьмем на себя.',
  'items-solution__titl_happycons': 'Счастливые консультации',
  'items-solution__text_consulations': 'Проводите консультации и получайте услуги на основе вашей записи. Вернитесь к здоровью.',
  'titl-doctor__name': 'Др. Халид Аббед',
  'titl-doctor__rating': 'Кардиолог (MBBS) 5.0',
  'item-doctor__text': 'Опыт',
  'item-doctor__number': '5 лет',
  'item-doctor__text2': 'Пациенты',
  'item-doctor__text3': 'Отзывы',
  'item-doctor__number': '3.5K',
  'item-doctor__number': '2.5K',
  'footer-doctor__text': 'Больница Mayo Clinic',
  'main-dictor__titl': 'Лучшие качественные услуги с нашими опытными врачами',
  'main-dictor__text': 'С нашими лучшими врачами мы способны предоставить лучшие медицинские услуги выше среднего. У нас есть высококвалифицированные врачи, так что не волнуйтесь. Они также очень талантливы в своих областях.',
  'services-doctor__servis': 'Ищите своего специалиста и проводите онлайн-консультации везде',
  'services-doctor__servis2': 'Консультация с нашими лучшими специалистами',
  'services-doctor__servis3': 'Врачи доступны 24/7',
  'main-dictor__button': 'Исследовать специалистов',
  'header-service__titl': 'Наши услуги',
  'header-service__text': 'Наши врачи обладают высокой квалификацией и гарантированно помогут вам восстановиться от болезни.',
  'item-service__cardiology': 'Кардиология',
  'header-service__text_cardiology': 'Наши кардиологи опытны в диагностике и лечении заболеваний сердечно-сосудистой системы.',
  'item-service__pulmonology': 'Пульмонология',
  'item-service__text_pulm': 'Наши пульмонологи опытны в диагностике и лечении заболеваний органов дыхания.',
  'item-service__titl_medecine': 'Медицина',
  'item-service__text_medecine': 'Наши врачи по медицине опытны в диагностике и лечении болезней современной медицины.',
  'online__titl': 'Познакомьтесь с нашими сертифицированными онлайн-врачами',
  'online__text': 'Наши онлайн-врачи имеют в среднем 15 лет опыта и уровень удовлетворенности 98%, они действительно выделяют нас!',
  'body-ite__text': 'Стоматолог специалист',
  'body-ite__text2': 'Кардиолог специалист',
  'body-ite__text3': 'Невролог специалист',
  'body-ite__text4': 'Онколог специалист',
  'explore_all_doctors': 'Исследовать всех врачей',
  'body-apps__titl': 'Мобильные приложения доступны. Скачайте HealthCare бесплатно!',
  'body-apps__text': 'Получайте доступ к врачу по требованию на своем телефоне с бесплатным мобильным приложением HealthCare. Скачайте и зарегистрируйтесь в нашем приложении бесплатно и чувствуйте себя в безопасности вместе со всей семьей.',
  'rigth-footer__titl': 'Подпишитесь на рассылку',
  'rigth-footer__text': 'Подпишитесь на получение советов, новых направлений и эксклюзивных акций.',
  'rigth-footer__button': 'Подписаться',
  'category__item_home': 'Главная',
  'category__item_about': 'О нас',
  'category__item_services': 'Услуги',
  'category__item_reviews': 'Отзывы',
  'category__item_article': 'Статьи',
  'left-footer__adress': 'Метейри, 3689 улица Бассел, Луизиана, США',
  'left-footer__tell': 'Свяжитесь с нами: 225-788-5489',
  'futer__licenzion': '© 2021 Healthcare - Все права защищены.',
  'futer__priv-item': 'Конфиденциальность',
  'futer__priv-item2': 'Безопасность',
  'futer__priv-item3': 'Условия использования',
  'items-solution__titl': 'Найдите лучшего врача',
  'clients__titl': 'Смотрите, что наши клиенты говорят о нас',
  'item-clients__text': 'Телемедицина развивается благодаря цифровым технологиям, и приложение DocTime для телемедицины произвело настоящую революцию. революцию в медицине специально для перенаселенной страны, где виртуальная палата может быть создана в любом месте по всей стране',
  'item-clients__text2': 'Я обратился к своему лечащему врачу по поводу болей в животе. Врач сказал, что мне необходимо обратиться к гастроэнтерологу. Раньше я обзванивал несколько кабинетов, чтобы записаться на прием в удобное для меня время.',
  'item-clients__text3': 'Забота о здоровье каждый раз становится моей суперсилой...! Я считаю DocTime отличной телемедицинской платформой с виртуальной комнатой ожидания, видеоконсультациями, электронными рецептами, прекрасно продуманным пользовательским интерфейсом. Спасибо.',
  'body-apoitment__titl': 'Это время изменить свою жизнь сегодня',
  'book_an_appoinment': 'Записаться на прием',
  'category__titl': 'Категории',
  'about__item': 'Партнеры',
  'about__item2': 'Карьера',
  'about__item3': 'Нажим',
  'about__item4': 'Сообщество',
  'about__titl': 'Подробнее', 
  'switch__theme': 'Сменить тему',
    },
  };

getTranslate();